name: Docker

on:
#  workflow_call: #Permite que esse workflow seja chamado por outros workflows, como o "go.yml" por exemplo.
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #Utiliza dados que estão aramanzenados no ambiente

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3 #Configura o ambiente para construção de imagens Docker

    - name: Download a build artifact
      uses: actions/download-artifact@v4 #Baixa os artefatos gerados por outros jobs, como o "build" do "go.yml"
      with:
        name: go-artifact #Especifica o nome do artefato a ser baixado, que deve corresponder ao nome definido no job "build" do "go.yml"

    - name: Docker Login
      uses: docker/login-action@v3 #Realiza login no Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }} #Utiliza o nome de usuário armazenado nos segredos do repositório
        password: ${{ secrets.DOCKER_PASSWORD }} #Utiliza a senha armazenada nos segredos do repositório
    
    - name: push Docker Image
      uses: docker/build-push-action@v3 #Constrói e envia a imagem Docker para o Docker Hub
      with:
        context: . #Define o contexto de construção como o diretório atual
        file: ./Dockerfile #Especifica o caminho para o Dockerfile a ser utilizado na construção da imagem
        push: true #Habilita o envio da imagem após a construção
        tags: joaomendes3822/my-go-app:${{ github.run_number }} #Define a tag para a imagem Docker, utilizando o número da execução do workflow para garantir que cada imagem seja única
        registry: docker.io #Especifica o registro Docker, que é o Docker Hub neste caso