name: Entrega continua

#Workflow Call: O evento "workflow_call" é utilizado para permitir que este workflow seja chamado por outros workflows. Isso é útil para criar uma estrutura modular, onde diferentes partes do processo de CI/CD podem ser definidas em arquivos separados e reutilizadas conforme necessário.
on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

#Obtendo arquivo da tarefa: Essa etapa utiliza o comando "aws ecs describe-task-definition" para obter a definição da tarefa do Amazon ECS. A definição da tarefa é um arquivo JSON que descreve como a aplicação deve ser executada no cluster ECS, incluindo informações sobre os contêineres, recursos e variáveis de ambiente. O resultado do comando é salvo em um arquivo chamado "task-definition.json" para uso posterior.    
    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition myapp-task:$(( github.run_number )) --query taskDefinition > task-definition.json
    
#Copia do task definition: Antes de modificar o arquivo "task-definition.json", é feita uma cópia de backup para garantir que a versão original do arquivo seja preservada. Isso é importante para evitar perda de dados ou configurações caso algo dê errado durante o processo de modificação.
    - name: copia do task definition
      run: cp task-definition.json task-definition-backup.json.bak
    
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: joaomendes3822/my-go-app:${{ github.run_number }} #Aqui, a tag da imagem Docker é atualizada para refletir a nova versão da aplicação, utilizando o número da execução do workflow para garantir que cada imagem seja única.
        environment-variables: |
          DBHOST=${{ secrets.DBHOST }}
          DBUSER=${{ secrets.DBUSER }}
          DBPASSWORD=${{ secrets.DBPASSWORD }}
          DBNAME=${{ secrets.DBNAME }}
          DBPORT=${{ secrets.DBPORT }}
          DBPORT=8000
          
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: myapp-service
        cluster: myapp-cluster
        wait-for-service-stability: true

    - name: Request test
      continue-on-error: true #Essa opção é usada para permitir que o workflow continue mesmo que esta etapa falhe. Isso é útil para evitar que o workflow seja interrompido devido a falhas temporárias ou problemas de conectividade durante a fase de teste.
      run: echo "REQUEST=0" >> $GITHUB_ENV ; sleep 30s ; wget URL_DO_SEU_ENDPOINT:porta/caminho || echo "REQUEST=1" >> $GITHUB_ENV
    
#Rollback: Se a etapa de teste falhar, o workflow irá para a etapa de rollback, onde a definição da tarefa do Amazon ECS é restaurada para a versão de backup. Isso garante que a aplicação volte a funcionar com a configuração anterior, minimizando o impacto de falhas na implantação.
    - name: Deploy Amazon ECS task definition - Rollback
      if: ${{ env.REQUEST != 0 }}
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition-backup.json.bak
        service: myapp-service
        cluster: myapp-cluster
        wait-for-service-stability: true